MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  BACKBONE: 'resnet50'
  METHOD: 'DE_FasterRCNN_OIM'
  PRETRAIN_PATH: '/root/.torch/models/resnet50-19c8e357.pth'



INPUT:
  MIN_MAX_SIZE: [900,1500]  #900,1500 default
  PROB: 0.5 # random horizontal flip


DATASETS:
  NAMES: ('CUHK_SYSU')

DATALOADER:

  BATCH_SIZE: 2
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'  #Adam,SGD
  MAX_EPOCHS: 40
  BASE_LR: 0.0003

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005


  STEP_SIZE: 8
  STEPS: [40, 70]
  GAMMA: 0.5

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'step' #constant
  WARMUP_GAMMA: 0.2
  WARMUP_DECAY_STEP: 5

  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 20
  EVAL_PERIOD: 40

  DOUBLE_BIAS: 0
  MOMENTUM: 0.9
  LR_DECAY_MILESTONES: None


TEST:
  IMS_PER_BATCH: 128


OUTPUT_DIR: "/root/proj/JMS_OIM/de_outputs"
RESUME: ''
APEX: ''

